### ISSUE TITLE
Merge CONTRIBUTING.md with README.md

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2015#10]
When a possible contributor sees the default repo view, based on the README.md, he doesn't see how to format contributions.

If we merge both files or append the content of CONTRIBUTING.md to README.md, it is viewable on first sight.

Any opinions on that?

**Comment by mathiasbynens** [comment]
`CONTRIBUTING.md` is the de facto standard for contribution guidelines. https://github.com/blog/1184-contributing-guidelines `README.md` should only contain information that is useful to lurkers, IMHO.

**Comment by YASME-Tim** [comment]
Adding a Contributing section as in https://github.com/puppetlabs/puppet#developing-and-contributing should fix this issue.

**Comment by YASME-Tim** [comment]
Ok I added a reference for CONTRIBUTING.md to README.md. Please close this Issue if you are OK with this decision.
