### ISSUE TITLE
SECURINETS QUALS CTF 2015: BE GENIOUS WRITE-UP

### ISSUE THREAD

**Issue by rezk2ll** [ctfs/write-ups-2015#101]
hello,
SECURINETS QUALS CTF 2015: BE GENIOUS WRITE-UP

https://rezk2ll.wordpress.com/2015/03/24/securinets-quals-ctf-2015-be-genious-write-up/

**Comment by YASME-Tim** [comment]
Just open one issue with all links next time, please...
