### ISSUE TITLE
SECURINETS QUALS CTF 2015: CRACK1 WRITE-UP

### ISSUE THREAD

**Issue by rezk2ll** [ctfs/write-ups-2015#103]
hello ,
SECURINETS QUALS CTF 2015: CRACK1 WRITE-UP

https://rezk2ll.wordpress.com/2015/03/24/securinets-quals-ctf-2015-crack1-write-up/

**Comment by YASME-Tim** [comment]
Thanks @rezk2ll - next time one issue for all please :)

**Comment by rezk2ll** [comment]
okay sorry for that :)
have a nice day.
