### ISSUE TITLE
Fix insomni-hack-ctf-2015 README.mds to conform the default structure

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2015#110]
The root README.md has a duplicate missing section. The task README.mds don't follow the original structure (Header with Description/Points etc, Description in Points, Files are referenced, Missing Write-up and Other write-ups and resources sections).

**Comment by bcyrill** [comment]
Should be fixed by pull requests #113, #114, #115, #116, #117, #118, #119, #120 and #121
