### ISSUE TITLE
0ctf

### ISSUE THREAD

**Issue by mathiasbynens** [ctfs/write-ups-2015#124]
https://ctf.0ops.sjtu.cn/
https://ctftime.org/event/198

Some write-ups:

* https://hexpresso.wordpress.com/2015/03/30/0ctf-2015-treasure-50-writeup/
* https://hexpresso.wordpress.com/2015/03/30/0ctf-2015-forward-250-writeup/

**Comment by YASME-Tim** [comment]
Coming, got it locally, just haven't had time yet to edit/check

**Comment by mathiasbynens** [comment]
Feel free to commit, I can edit if you don’t have the time

**Comment by GeoHanKein** [comment]
0ctf please!!

**Comment by cernica** [comment]
For Golden Mac 2 http://whit3hat.com/Golden-Mac-2-writeup.pdf

**Comment by volpino** [comment]
RSAQuine http://tasteless.eu/2015/03/0ctf-2015-rsaquine/

**Comment by pwntester** [comment]
Golden Mac 1 http://www.pwntester.com/blog/2015/03/30/0ctf-2015-golden-mac-1-web-300/
Golden Mac 2 http://www.pwntester.com/blog/2015/03/30/0ctf-2015-golden-mac-2-web-300/
X-Y-Z http://www.pwntester.com/blog/2015/03/30/0ctf-2015-x-y-z/
Lily http://www.pwntester.com/blog/2015/03/30/lily-web-200/
Forward  http://www.pwntester.com/blog/2015/03/30/0ctf-short-write-ups/

**Comment by YASME-Tim** [comment]
Thanks guys. Will add the writeup links, sorry for the wait :/.

**Comment by mathiasbynens** [comment]
@YASME-Tim Thanks for your work on this!
