### ISSUE TITLE
codegate-ctf-2015/pwnable/olive-and-mushroom-pizza writeup

### ISSUE THREAD

**Issue by mokipcs** [ctfs/write-ups-2015#180]
http://filedu.mp/2bb128905bd56d8c/write-up.txt

**Comment by dhanvi** [comment]
Thanks for the writeup link :+1: @mokipcs

**Comment by mokipcs** [comment]
Thanks for keeping track of all the CTF related stuff.

**Comment by dhanvi** [comment]
@mokipcs credit goes to @mathiasbynens and @YASME-Tim for the repos :smile:
