### ISSUE TITLE
Anyone can add schoolCTF

### ISSUE THREAD

**Issue by abdilahrf** [ctfs/write-ups-2015#214]
Scoreboard : http://school-ctf.org/#rating-ref

**Comment by dhanvi** [comment]
@YASME-Tim hope you are doing it, if not I will do it

**Comment by YASME-Tim** [comment]
@dhanvi I did not record any descriptions/files for it so anyone can do it, if it's still up.

**Comment by abdilahrf** [comment]
@dhanvi  i'd love to do it , but i've a bit busy this week 
i appreciate if you do it thanks

**Comment by dhanvi** [comment]
@abdilahrf I will do but I don't see any web challenges up

**Comment by abdilahrf** [comment]
@dhanvi maybe your connection , in here still up

**Comment by dhanvi** [comment]
closed it here 1ebe3a321e4b667117b04904af2128b8f138eb2f

may be because I am under a firewall which doesn't allow all the ports :(
@abdilahrf  would you mind adding the web source

**Comment by YASME-Tim** [comment]
We are still missing several tasks (e.g. admin, crypto/lazy etc) for this CTF. Not everything was added. Reopened

**Comment by YASME-Tim** [comment]
Looks like there is a School CTF Spring and a School CTF (Winter) and some challenges from Spring have been used again for the Winter version? Either I'll combine all challenges in one directory or split them in two. I'll guess the former does the job for now

**Comment by YASME-Tim** [comment]
I've split them. The challenge's names did not match and I think they used new challenges for School Winter - So it was indeed complete :)
