### ISSUE TITLE
Add some schoolctf writeups

### ISSUE THREAD

**Issue by abdilahrf** [ctfs/write-ups-2015#228]
http://www.hasnydes.us/2015/05/schoolctf-unusual-redirection-300pts/
http://www.hasnydes.us/2015/05/schoolctf-stored-pass-100pts/
http://www.hasnydes.us/2015/05/schoolctf-shop-of-goodness-100pts/
http://www.hasnydes.us/2015/05/schoolctf-tacticus-abilitus-100pts/
http://www.hasnydes.us/2015/05/schoolctf-strange-spam-100pts/
http://www.hasnydes.us/2015/05/schoolctf-school-incident-150pts/
http://www.hasnydes.us/2015/05/schoolctf-tricky-authorization-200pts/
http://www.hasnydes.us/2015/05/schoolctf-not-weird-selfie-200pts/
http://www.hasnydes.us/2015/05/schoolctf-weird-selfie-100pts/
http://www.hasnydes.us/2015/05/schoolctf-hidden-file-200pts/

I'cant make pull request because have a repository conflict , thanks 
@dhanvi @YASME-Tim

**Comment by dhanvi** [comment]
@abdilahrf you better check this #198 to reset your fork :smile: 

hope this helps you :+1:

**Comment by abdilahrf** [comment]
thanks for that , really helping :+1:

**Comment by dhanvi** [comment]
@abdilahrf closed it here 988f1bbd5f9447928455c9f467861e4e2d41318f

Well hope with my little help you can reset your fork and create your self new pull request next time :smile:
