### ISSUE TITLE
ASIS Quals Skeleton

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2015#229]
This is just a notice - I already created and committed the skeleton and included all files needed. Will upload it as soon as CTF ends - please do not cause a merge conflict :)

**Comment by dhanvi** [comment]
@YASME-Tim now the ctf is over you can push them :)

**Comment by volpino** [comment]
Simple algorithm writeup
http://capturetheswag.blogspot.com.au/2015/05/asis-ctf-2015-simplealgorithm-100-point.html

**Comment by YASME-Tim** [comment]
Thanks @volpino

**Comment by dhanvi** [comment]
@YASME-Tim I was doing the same and now got a conflict :P

@volpino better create a new issue for a new link :+1: and thanks for the link :smile:

**Comment by YASME-Tim** [comment]
@dhanvi Nice, good to know someone else is keeping track of all tasks :)!
