### ISSUE TITLE
the files of related challenge have not been updated?

### ISSUE THREAD

**Issue by naijim** [ctfs/write-ups-2015#247]
After checking the description I find out that some files have not been uploaded to Github. For example for reversing challenges there should be a bin file uploaded. It is intended to make this repository clean? After the CTF(the CTF website shutdown) there would be no place for the guys who want to try out the challenge to find the bin file...
Do you plan to solve this problem by setting up another repo or just leave it?

**Comment by YASME-Tim** [comment]
@naijim Which CTF + files do you mean? We don't include files bigger than 10-15MB, else the repo would become too big to clone. I have most files locally and can upload them elsewhere (e.g. mega), if it is needed.

**Comment by naijim** [comment]
check [this](https://github.com/ctfs/write-ups-2015/tree/master/defcon-qualifier-ctf-2015/babys-first/babycmd). The link in the description points to another website. I think there should be another place to hold them(like you say mega or dropbox).

**Comment by YASME-Tim** [comment]
@naijim The files are already in the repo :). I think you missed them, here is [babycmd](https://github.com/ctfs/write-ups-2015/blob/master/defcon-qualifier-ctf-2015/babys-first/babycmd/babycmd_3ad28b10e8ab283d7df81795075f600b) for example

**Comment by naijim** [comment]
You should check other challenges too. I randomly check some CTF events, like asis reversing challenges. Some files are still not uploaded. I close this issue.

**Comment by YASME-Tim** [comment]
Well I certainly check that I include every file thats <10MB, before I upload the whole structure/skeleton. You can of course check everything again manually. Tell me which files are not uploaded yet. Maybe if I change the references from remote to local, it becomes more obvious..

**Comment by dhanvi** [comment]
@naijim Well we do check weather all the files were verified or not in the repo most of the time :smile: 

For example as you pointed in ASIS I have verified them all of the reversing files are present :smile: 

![screenshot from 2015-05-18 18 42 33](https://cloud.githubusercontent.com/assets/6671379/7681448/02e99836-fd8e-11e4-845e-8c1cf851dda4.png)

Only issue there was that the README is still pointing to the ASIS website (Which doesn't matter IMO)

AlSO NEXT TIME WHEN YOU RAISE A ISSUE PLEASE MAKE SURE THAT YOU PIN-POINT THE ISSUE (FOR EXAMPLE THE FOO-CTF-REVERSING FILE IS MISSING) DON'T SIMPLY JUST COMPLAIN (HOPE YOU GOT ME)
