### ISSUE TITLE
Writeup ASIS Quals

### ISSUE THREAD

**Issue by devforge** [ctfs/write-ups-2015#249]
Hi,

here are our writeups for ASIS Quals 2015
Secret Message: https://ucs.fbi.h-da.de/writeup-asis-ctf-quals-2015-secret-message/
Keka Bomb: https://ucs.fbi.h-da.de/writeup-asis-ctf-quals-2015-keka-bomb/

**Comment by devforge** [comment]
Strange Authen: https://ucs.fbi.h-da.de/writeup-asis-ctf-quals-2015-strange-authen/
Best Photo: https://ucs.fbi.h-da.de/writeup-asis-ctf-quals-2015-best-photo/

**Comment by dhanvi** [comment]
@devforge Thanks for giving Links :smile:
