### ISSUE TITLE
README.md "Let us know" link redirects to the 2014 repo

### ISSUE THREAD

**Issue by libmaru** [ctfs/write-ups-2015#261]
README.md:

    Did you just publish a CTF write-up? [Let us know](https://github.com/ctfs/write-ups/issues/new)

The link
`https://github.com/ctfs/write-ups/issues/new`
redirects to
`https://github.com/ctfs/write-ups-2014/issues/new`

**Comment by dhanvi** [comment]
Well the readme was copied from the previous write-up repos and we renamed the writeup repo to write-up 2014 as it contained the challenges starting 2014 

btw for ur info we are trying to go back in history by even creating ctfs/write-ups-2013 If you have anything to share please try to add it there :smile: 

and thanks for raising issue
