### ISSUE TITLE
DEF CON Qualifier 2015: wibbly-wobbly-timey-wimey writeup

### ISSUE THREAD

**Issue by morganzz** [ctfs/write-ups-2015#267]
another write up for wibbly wobbly timey wimey ~
http://blog.morganz.me/blog/2015/05/23/def-con-ctf-qualifier-2015-wibbly-wobbly-timey-wimey-writeup/

**Comment by YASME-Tim** [comment]
Thanks @morganzz

**Comment by dhanvi** [comment]
Well I was doing the same thing and got a conflict :smile:

**Comment by YASME-Tim** [comment]
@dhanvi Arg, sorry :)

**Comment by dhanvi** [comment]
No problem next time I will assign it myself so that we won't get into conflict again :smile: 

have you checked out this ctf https://ctftime.org/event/220 should I raise a issue for it
