### ISSUE TITLE
I think we should build a website

### ISSUE THREAD

**Issue by lionaneesh** [ctfs/write-ups-2015#272]
Hey,

I think we  (I volunteer) should build a website that would accompany this repository. Github is great, but it lacks a good UI to view writeups and any kind of writeup specific searches. I was thinking of using the Guthub API and making a website that pulls up all the content from the repo. We can maybe have it sync once a day. 

Thoughts?

**Comment by dhanvi** [comment]
Cool that you volunteered may be you can use github pages for it 

@mathiasbynens @YASME-Tim  

FYI we already have https://github.com/ctfs/write-ups-tools and a good book at https://ctfs.github.io/resources/

but a website beats them all :smile:

**Comment by lionaneesh** [comment]
Is there anyone else interested?

**Comment by dhanvi** [comment]
Seems like they are all busy :smile:

**Comment by mathiasbynens** [comment]
The GitHub web UI for this repository is the website. I don’t think we need a second one, especially if it is maintained separately.

**Comment by YASME-Tim** [comment]
Invest your time in writing local write-ups instead ;)

**Comment by mathiasbynens** [comment]
> Invest your time in writing local write-ups instead ;)

This.
