### ISSUE TITLE
WhiteHat Wargame Challenge

### ISSUE THREAD

**Issue by abdilahrf** [ctfs/write-ups-2015#305]
List of all challenge here : https://wargame.whitehat.vn/Challenges
*still can be access although the ctf was end
can someone make placeholder for this event ?
use https://github.com/ctfs/write-ups-tools

**Comment by dhanvi** [comment]
I can do it, I just need some time :smile:

**Comment by dhanvi** [comment]
Just a small mistake in the above url the actual problems are here https://wargame.whitehat.vn/Contests/ChallengesContest/25

**Comment by dhanvi** [comment]
I have not edited the mark up stuff, I will fix them asap :+1:
