### ISSUE TITLE
Place holders for camp ctf 

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#313]
@YASME-Tim hope you can do it and I am assigning this to you 

and here is the link https://campctf.ccc.ac/login/#

**Comment by paruchuri** [comment]
Can you people add my CTF Write of CAMPCTF -2015
https://nuc13us.wordpress.com/2015/08/16/secret_file-150-cscamp-ctf-2015/?preview=true&preview_id=104&preview_nonce=5fe4cd830a&post_format=standard

**Comment by dhanvi** [comment]
@YASME-Tim are you working on this ? If not I will keep the place holders 

@paruchuri Thank you! for the link, I will add them once the place holders (files of ctf) are added to the repo

**Comment by YASME-Tim** [comment]
@dhanvi Yeah I am going to tackle this problem today

**Comment by dhanvi** [comment]
@YASME-Tim please add the place holders quickly or assign the issue to me
