### ISSUE TITLE
Place holders for IceCTF

### ISSUE THREAD

**Issue by lostkhaos** [ctfs/write-ups-2015#320]
I can make placeholders for flags 1 through 47 (up to Wiki & The Furious), but I know there's at least one more full set of challenges.

**Comment by dhanvi** [comment]
go ahead and create the place holders and create a pull request :smile: 

I will happily take the files :smile:

**Comment by dhanvi** [comment]
This looks similar to the picoctf :smile: 

also to me it looks that they are using the same frame work

**Comment by dhanvi** [comment]
@lostkhaos please don't waste your time working on this it's already placed in #324 by @kapaw

**Comment by lostkhaos** [comment]
Oh woah that was fast haha. Cheers.
