### ISSUE TITLE
Place holders for Inc0gnito CTF

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#322]
People who know Korean can help us by adding this ctf files and translating the description them to English

**Comment by guswns0528** [comment]
Hello, I think I can help you to translate. but, I don't have any descriptions.

**Comment by dhanvi** [comment]
The challenges are still up at http://ctf.inc0gnito.com/ @guswns0528 

you can use this tool to create the placeholders https://github.com/ctfs/write-ups-tools

**Comment by guswns0528** [comment]
The challenges are closed. I can't see anything.

**Comment by dhanvi** [comment]
try sending an email to the organizers by showing this issues / ask them in IRC

**Comment by dhanvi** [comment]
@guswns0528 Did you have any luck with the Challenges ?

**Comment by guswns0528** [comment]
Yes, I got descriptions, files, and others. But It's too hard to make time for it.
Maybe, It'll be done in the next weekend.

**Comment by dhanvi** [comment]
I do understand the time take to keep the placeholders @guswns0528 

If the descriptions are in English, email me all the files and I am currently not so busy and I can add them now :smile:

**Comment by dhanvi** [comment]
@guswns0528  Added them in #342
