### ISSUE TITLE
Writeup Web300 MMACTF 2015

### ISSUE THREAD

**Issue by 81glntd** [ctfs/write-ups-2015#333]
http://81glntd.blogspot.com/2015/09/writeup-web300-mmactf-2015.html

**Comment by dhanvi** [comment]
hey @tomvangoethem can you please assign the issue for your self before fixing it :smile: 

I was working on the same and I got a conflict 

PS:Can you add me to the owner group so that I can work on the writeup tools scripts little bit :smile:
