### ISSUE TITLE
Write-up for camp-ctf-2015/forensics/APT-incident-response-400

### ISSUE THREAD

**Issue by r8t** [ctfs/write-ups-2015#336]
Hey. Please find below a write-up for this challenge at http://dft-labs.eu/~ctf/CCCCAMP_2015/APT-incident-response/writeup.txt . Thanks.

**Comment by dhanvi** [comment]
Hi @r8t 

I have already added this writeup in this commit 81a5ffd0e638136bed8cfbaa0216d95c4ddcf9bc 

you can see the writeup added here https://github.com/ctfs/write-ups-2015/tree/master/camp-ctf-2015/forensics/APT-incident-response-400

Thank You! for the writeup link :smile:
