### ISSUE TITLE
Place holders for Defcamp CTF

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#378]
I will put them here as soon as the server is up :smile: 

If any one are interested in placing them put a comment here and you can do it

**Comment by dhanvi** [comment]
I am working on this one it will be done in few hours :+1:

**Comment by AndreiAvadanei** [comment]
Let me know if I can help :+1:

**Comment by dhanvi** [comment]
Sorry! for the delay placing the challenges, I was into some other work
