### ISSUE TITLE
Skeleton for TUM CTF Teaser

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2015#403]
We need all files and descriptions!

**Comment by YASME-Tim** [comment]
Looks like the hardworking @fariskhi resolved this issue in https://github.com/ctfs/write-ups-2015/commit/099445fd087d2f70f61e84eb972bf2e8203d8037 :+1: +1:

**Comment by dhanvi** [comment]
@fariskhi cool !
