### ISSUE TITLE
Hack.lu CTF 2015 PHP Golf team RandomsCTFTeam

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#414]
Hack.lu CTF 2015 PHP Golf team RandomsCTFTeam<br>
https://ctftime.org/writeup/2083<br>
https://github.com/RandomsCTF/write-ups/tree/master/Hack.lu%20CTF%202015/PHP%20Golf%20%5Bppc%5D%20(75)<br><br>

**Comment by YASME-Tim** [comment]
https://github.com/ctfs/write-ups-2015/commit/0e89eafa2e47eb3ff7a50b8bb54af433464f639d
