### ISSUE TITLE
Hack.lu CTF 2015 Bashful team RandomsCTFTeam

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#417]
Hack.lu CTF 2015 Bashful team RandomsCTFTeam<br>
https://ctftime.org/writeup/2086<br>
https://github.com/RandomsCTF/write-ups/tree/master/Hack.lu%20CTF%202015/Bashful%20%5Bweb%5D%20(200)<br><br>

**Comment by YASME-Tim** [comment]
https://github.com/ctfs/write-ups-2015/commit/0e89eafa2e47eb3ff7a50b8bb54af433464f639d
