### ISSUE TITLE
Hack.lu CTF 2015 Dr Bob team RandomsCTFTeam

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#418]
Hack.lu CTF 2015 Dr Bob team RandomsCTFTeam<br>
https://ctftime.org/writeup/2087<br>
https://github.com/RandomsCTF/write-ups/tree/master/Hack.lu%20CTF%202015/Dr.%20Bob%20%5Bforensics%5D%20(150)<br><br>

**Comment by YASME-Tim** [comment]
https://github.com/ctfs/write-ups-2015/commit/0e89eafa2e47eb3ff7a50b8bb54af433464f639d
