### ISSUE TITLE
Hack.lu CTF 2015 Petition Builder team peanuts

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#421]
Hack.lu CTF 2015 Petition Builder team peanuts<br>
https://ctftime.org/writeup/2090<br>
http://wapiflapi.github.io/2015/10/29/eight-byte-shell/<br><br>

**Comment by YASME-Tim** [comment]
https://github.com/ctfs/write-ups-2015/commit/0e89eafa2e47eb3ff7a50b8bb54af433464f639d
