### ISSUE TITLE
WhiteHat Grand Prix  Qualification Round 2015 Can Tho and Ho Chi Minh City team Evil Genius

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#424]
WhiteHat Grand Prix &ndash; Qualification Round 2015 Can Tho and Ho Chi Minh City team Evil Genius<br>
https://ctftime.org/writeup/2093<br>
[click on title to read at ctftime.org]<br><br>

**Comment by abdilahrf** [comment]
the actual link not showing , http://81glntd.blogspot.com/2015/10/writeup-web100-web150-whitehat.html
