### ISSUE TITLE
Hack.lu CTF 2015 Solution Checker

### ISSUE THREAD

**Issue by Septyem** [ctfs/write-ups-2015#430]
Hack.lu CTF 2015 Solution Checker

https://github.com/Septyem/CTF-writeups/tree/master/hack.lu2015/SolutionChecker

Not in detail, but I hope it helpful

**Comment by YASME-Tim** [comment]
@Septyem Do you still have the flag? This is a complete writeup that tells the reader how the challenge is done without any open questions right?

**Comment by Septyem** [comment]
@YASME-Tim Yes, I have the flag stored but not on hand so I can't update it now. And I think it contains all the information to solve this challenge, at least for experienced CTF players.

**Comment by Septyem** [comment]
The flag has been added now

**Comment by YASME-Tim** [comment]
@Septyem Sorry, did take a bit longer as usual. Added - thank you for your writeup :)
