### ISSUE TITLE
problem Misaka Mikoto

### ISSUE THREAD

**Issue by nephop** [ctfs/write-ups-2015#447]
problem Misaka Mikoto (cryptography)

Solved by 331 teams.

My friends like anime way too much . . . they decided that to give me an encoded message, but I can't solve it because I'm not a weeb!

hint:railguns are cool

Solution: "rail" cipher

https://git.gitbook.com/johnwig/misaka-mikoto.git

**Comment by YASME-Tim** [comment]
Which ctf is this for again? @nephop
