### ISSUE TITLE
9447 Security Society CTF 2015 premonition team pony7

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#543]
9447 Security Society CTF 2015 premonition team pony7<br>
https://ctftime.org/writeup/2181<br>
https://wiki.inpt.fr/ctf:public:9447:premonition<br><br>

**Comment by arthaud** [comment]
I made the pull request https://github.com/ctfs/write-ups-2015/pull/544

**Comment by YASME-Tim** [comment]
Closed by @arthaud
