### ISSUE TITLE
9447 Security Society CTF 2015 darklang team b01lers

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#552]
9447 Security Society CTF 2015 darklang team b01lers<br>
https://ctftime.org/writeup/2187<br>
https://b01lers.net/challenges/9447%20CTF%202015/darklang/79/<br><br>

**Comment by YASME-Tim** [comment]
@dhanvi can you please fix your ifttt and/or answer at gitter?

**Comment by dhanvi** [comment]
Usually I used to get an email when someone mentioned me on Gitter, I missed that email / Gitter didn't send me one
I have answered about the ifttt on Gitter
