### ISSUE TITLE
SECCON 2015 Online CTF QR puzzle (Web) (Misc 400p) team p4

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#609]
SECCON 2015 Online CTF QR puzzle (Web) (Misc, 400p) team p4<br>
https://ctftime.org/writeup/2231<br>
https://github.com/p4-team/ctf/tree/master/2015-12-05-seccon/qr_web_400#eng-version<br><br>

**Comment by YASME-Tim** [comment]
Fixed them already..
