### ISSUE TITLE
SECCON 2015 Online CTF QR puzzle (Nonogram) (Misc 300p) team Capture the Swag

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#612]
SECCON 2015 Online CTF QR puzzle (Nonogram) (Misc, 300p) team Capture the Swag<br>
https://ctftime.org/writeup/2233<br>
http://capturetheswag.blogspot.com.au/2015/12/seccon-2015-nonogram-300-point.html<br><br>

**Comment by YASME-Tim** [comment]
Closed here https://github.com/ctfs/write-ups-2015/commit/302e97db5680c216f92cc8cf8ae9b5c63e1d3aa2
