### ISSUE TITLE
fearg0t

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#630]
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr" xml:lang="en">sploit for my ITD task at <a href="https://twitter.com/hashtag/32c3ctf?src=hash">#32c3ctf</a> : <a href="https://t.co/Qpo7e5I5Ju">https://t.co/Qpo7e5I5Ju</a></p>
&mdash; Fear (@fearg0t) <a href="https://twitter.com/fearg0t/status/681929853839536128">December 29, 2015</a>
</blockquote>

**Comment by YASME-Tim** [comment]
Already added :)
