### ISSUE TITLE
New 32c3 readme write up 

### ISSUE THREAD

**Issue by mashirogod** [ctfs/write-ups-2015#664]
http://mashirogod.github.io/blog/2015/12/31/32c3-pwn-200-readme-write-up/

**Comment by mashirogod** [comment]
I am not good at English.
 So I can not express my mind well.
Please excuse me. :)

**Comment by YASME-Tim** [comment]
@mashirogod  Thanks! Don't be sorry :). I'll add it immediately, 1 second..
