### ISSUE TITLE
LiveOverflow

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#665]
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr" xml:lang="en">Video writeup of readme (pwnable 200) from <a href="https://twitter.com/hashtag/32c3ctf?src=hash">#32c3ctf</a>
There are many great writeups for it, but maybe this helps sb. <a href="https://t.co/4c63ECpQsP">https://t.co/4c63ECpQsP</a></p>
&mdash; LiveOverflow (@LiveOverflow) <a href="https://twitter.com/LiveOverflow/status/682563727674179585">December 31, 2015</a>
</blockquote>

**Comment by YASME-Tim** [comment]
@dhanvi Please have a look at gitter and disable it :)
