### ISSUE TITLE
32C3 CTF libdroid team GoN

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#666]
32C3 CTF libdroid team GoN<br>
https://ctftime.org/writeup/2256<br>
http://yous.be/2015/12/30/32c3-ctf-2015-libdroid-write-up/<br><br>

**Comment by YASME-Tim** [comment]
Solved [here](https://github.com/ctfs/write-ups-2015/commit/61f7f142255193c5ca46055e066aa35e7401de4e)
