### ISSUE TITLE
32C3 CTF Teufel team Gallopsled

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#683]
32C3 CTF Teufel team Gallopsled<br>
https://ctftime.org/writeup/2264<br>
http://ebfe.dk/ctf/2016/01/06/32c3-teufel/<br><br>

**Comment by YASME-Tim** [comment]
Solved here: https://github.com/ctfs/write-ups-2015/commit/f5a76af57709cd8ff1bac49a44cd610ba081e82f
