### ISSUE TITLE
Insomni'hack teaser 2016 smartcat1 team Capture the Swag

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2015#691]
Insomni'hack teaser 2016 smartcat1 team Capture the Swag<br>
https://ctftime.org/writeup/2270<br>
https://ctf.rip/insomnihack-teaser-2016-smartcat1-50-pt-web-challenge/<br><br>

**Comment by YASME-Tim** [comment]
Happy new year @dhanvi  ;)

**Comment by dhanvi** [comment]
@YASME-Tim 
from now on issues will be created in the 2016 repo irrespective of the year of ctf :)
