### ISSUE TITLE
Translate Indonesian ibteam blackvalentine ctf

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2015#70]
I can't speak Indonesian and all task descriptions are in Indonesian (I think). Please don't just Google Translate it :).

**Comment by dhanvi** [comment]
Hope @abdilahrf can do this for us as he had placed the place holders for the ctf :smile: if he knows Indonesian

**Comment by abdilahrf** [comment]
my english not a little bad :/ , but i will try to do

**Comment by abdilahrf** [comment]
i've sent, #72 just let me know if any grammar incorrect or anything else

**Comment by YASME-Tim** [comment]
I think it's OK now. If someone has issues with this CTF, we might reopen this issue. But for now, it's good enough ;)! Thanks @abdilahrf
