### ISSUE TITLE
New writeup for 2016-02-20-internetwache-ctf misc70

### ISSUE THREAD

**Issue by WhiteLightninggit** [ctfs/write-ups-2015#713]
Hi I've created new writeup here for latest CTF:

https://github.com/raccoons-team/ctf/tree/master/2016-02-20-internetwache-ctf/misc70

As its my first one, hope its correct:)

**Comment by tomvangoethem** [comment]
The write-up looks fine :)
We split repositories per year, so this one should go into [write-ups-2016](https://github.com/ctfs/write-ups-2016/). Any chance you could make a pull request where you either include a link to the write-up, or replicate it over there? You can find the appropriate files and folders in [internetwache-ctf-2016](https://github.com/ctfs/write-ups-2016/tree/master/internetwache-ctf-2016).

**Comment by dhanvi** [comment]
@tomvangoethem looks like it's a issue from our side as we specified the wrong url in the README.md of the 2016 repo which I have fixed it here https://github.com/ctfs/write-ups-2016/commit/fa45a7838d32b945a29f8469aa3c9d370cc0d040 

and I have shifted the issue to 2016 repo https://github.com/ctfs/write-ups-2016/issues/501
