### ISSUE TITLE
suggest to add sctf writeup

### ISSUE THREAD

**Issue by abdilahrf** [ctfs/write-ups-2015#79]
https://github.com/Superari/sCTF-2015

**Comment by dhanvi** [comment]
@abdilahrf can you create a pull request?

**Comment by abdilahrf** [comment]
@dhanvi  I can't separate the category

**Comment by dhanvi** [comment]
@abdilahrf It's not that hard to put the problem into a category, I can sort them out for you 

just add a comment to this issue if you find any thing difficult to sort the challenges 

(you can always put the challenge into misc if you think it's completely different or a mix of all )

**Comment by YASME-Tim** [comment]
Added by @abdilahrf , closed :)!
