### ISSUE TITLE
problems with windows commits

### ISSUE THREAD

**Issue by stypr** [ctfs/write-ups-2015#80]
some of folder names are illegal on windows (specifically colon) and I can't commit some of files because of that. Can I change folder names for these ones and then commit?

![error](https://cloud.githubusercontent.com/assets/6625978/6679295/2d6b8fb8-cc1c-11e4-83da-ac519cbf66c1.PNG)

**Comment by YASME-Tim** [comment]
@stypr yeah, just rename them

**Comment by mathiasbynens** [comment]
Replace `:` with `-`
