### ISSUE TITLE
Securinet Challenges and Writeups

### ISSUE THREAD

**Issue by apsdehal** [ctfs/write-ups-2015#98]
Can you add placeholders for Securinet CTF?

**Comment by dhanvi** [comment]
@apsdehal Can create a pull request placing all the place holders as per our [Contribution Guide](https://github.com/ctfs/write-ups-2015/blob/master/CONTRIBUTING.md) 

Also the [ctf](http://www.securinets.com/ctf) looks like in French, so we need a translator too (google translator cann't be always correct)

**Comment by YASME-Tim** [comment]
It's over already? Sec, I'll upload it, I got this
